### ISSUE TITLE
Installation difficulty

### ISSUE THREAD

**Issue by kshedden** [JuliaIO/ImageIO.jl#1]
Does anyone know how to resolve this?  My Julia version is 1.2.0

julia> Pkg.add("ImageIO")                                                                                                                                                     Resolving package versions...                                                                                                                                               ERROR: Unsatisfiable requirements detected for package ImageIO [82e4d734]:                                                                                                    ImageIO [82e4d734] log:                                                                                                                                                      ├─possible versions are: 0.1.0-0.1.1 or uninstalled                                                                                                                          ├─restricted to versions * by an explicit requirement, leaving only versions 0.1.0-0.1.1                                                                                     └─restricted by julia compatibility requirements to versions: uninstalled — no versions left

**Comment by IanButterworth** [comment]
Julia versions < 1.3 are unsupported. Can you try updating to 1.3.1 ?

If you need to remain on 1.2, you can use ImageMagick

**Comment by kshedden** [comment]
Yes, that resolved it.  Thanks for the quick response.
