### ISSUE TITLE
Output swatches are reduced due to the large size

### ISSUE THREAD

**Issue by Jeries27** [JuliaIO/ImageIO.jl#16]
Every image that I try to add (from url, storage or TestImages) doesn't show the correct pixels, else they are reduced/compressed. Also the type of image is Array{RGB{FixedPointNumbers.Normed{UInt8,8}},2}. Shouldn't it be RGBX?

**Comment by johnnychen94** [comment]
Could you provide a more informative description? For example, which image from TestImages. What output you get, and what are the expected results.

If you need to show an image, you also need to use `ImageShow` (and optionally ImageTransformations).

**Comment by Jeries27** [comment]
ImageShow solved the first problem.
(Pkg.add + using ImageShow) 
(I tried to get the lighthouse picture at first and it had reduced pixels)
Thank you

**Comment by johnnychen94** [comment]
If I understand it correctly, the X channel in `RBGX`/`XRGB` are dummy values only for memory alignment, so there's no actual difference to use either `RGB` or `RGBX`.

```julia
x = rand(RGB{Float32})
RGBX(x) == x # true
```
