### ISSUE TITLE
Add TiffImages for TIFFs

### ISSUE THREAD

**Issue by IanButterworth** [JuliaIO/ImageIO.jl#18]
We should add https://github.com/tlnagy/TiffImages.jl so that we can support TIFFs

@tlnagy is there anything preventing this on the TiffImages side?

**Comment by tlnagy** [comment]
Nope! `TiffImages` should cover most common use cases. Do I need to adjust the user-facing API to add support for ImageIO?

One key limitation is the lack of support for LZW compression/decompression. I'm working on a separate package implementing LZW but it's not quite ready to be integrated in `TiffImages` yet.
