### ISSUE TITLE
Writing image to stream

### ISSUE THREAD

**Issue by SimonDanisch** [JuliaIO/ImageIO.jl#2]
Hey, I tried switching to ImageIO, but it turned out that this functionality is missing:
```Julia
 FileIO.save(FileIO.Stream(FileIO.format"PNG", io), img)
```
Seems like it would be easy to support, since the image packages expect an io anyways?

**Comment by IanButterworth** [comment]
Sorry, missed this. I agree. 
I've started backwards with adding the wrappers here #3 and will try to craft the PNGFiles backend support

**Comment by IanButterworth** [comment]
Added via #3 and about to be released as 0.2.0
