### ISSUE TITLE
unwrap `DenseTaggedImage` to normal `Array`?

### ISSUE THREAD

**Issue by johnnychen94** [JuliaIO/ImageIO.jl#25]
```julia
julia> testimage("camera") |> summary
"512×512 TiffImages.DenseTaggedImage{ColorTypes.Gray{FixedPointNumbers.N0f8}, 2, UInt32, Matrix{ColorTypes.Gray{FixedPointNumbers.N0f8}}}"
```

It looks like `TiffImages` has its own array type, which is okay. I know it would lose some information, but I'm wondering if it's reasonable to unwrap it to a normal array?

A related issue is https://github.com/JuliaImages/TestImages.jl/issues/112

cc: @tlnagy

**Comment by IanButterworth** [comment]
Yeah. I think given the way FileIO lazy loads, it may be a UX requirement that load returns a format that doesn't depend on the package. 

This wouldn't need to change all the TiffImages funcs, just the ones ImageIO taps into. I guess that could happen in either ImageIO or TiffImages

**Comment by tlnagy** [comment]
I think, in general, most people won't care about the TIFF tags when they load an image via `ImageIO` so I think returning an `Array` is the right call for dense, regularized TIFFs.

That said, there are advanced forms of TIFFs that have hierarchies that don't map nicely onto `Array`s (pyramidal images, GeoTIFFs etc), which `TiffImages` has various levels of support for. Question is, what should we do if someone attempts to load one of those images? 

1. Return custom types for all TIFFs (**current default**)
2. Force the `Array` conversion for all TIFFs (would probably need to happen on load on `TiffImages` side)
3. Return `Array` for dense images and custom types for other types?

My gut feeling is that option 2 is the best, but also the most complex.

**Comment by IanButterworth** [comment]
Yeah, 2 sounds good. It would be nice if we could visibly state somewhere that for more advanced TIFF functionality, users should use TiffImages directly. Perhaps the ImageIO docstring and readme would be a good start.

**Comment by tlnagy** [comment]
Thanks @johnnychen94 for taking a stab at this. I think it's a decent first pass implementation of 2. 

Longer term, `TiffImages` should know about the conversion prior to starting to load the file so it can load it in a compatible way, i.e. only the largest slice in a pyramidal image, etc. This would be more efficient/more general than doing the conversion post-hoc.

**Comment by johnnychen94** [comment]
Here's my idea in mind:

We could optionally let `TiffImages` accept some keyword so that users can use, for example, `load(file; limited=true)` to directly load and return `Array`, and `load(file; limited=false)` to load and return TiffImages' own array type. When TiffImages' side is ready, we can then specialize the method `canonical_type` for tiff image and TIFFImages' array type.
