### ISSUE TITLE
[RFC] make v0.0.1 release with no codes

### ISSUE THREAD

**Issue by johnnychen94** [JuliaIO/ImageIO.jl#33]
This package is more performant than ImageMagick, this package is also lightweight. It would be good to use this package as an image IO backend during CI.

However, for packages that want to maintain backward compatibility to Julia 1.0. It simply can't do so because CI will complain about this. For example,

```julia
   Testing ImageUtils
 Resolving package versions...
ERROR: Unsatisfiable requirements detected for package ImageIO [82e4d734]:
 ImageIO [82e4d734] log:
 ├─possible versions are: [0.1.0-0.1.1, 0.2.0, 0.3.0-0.3.1, 0.4.0-0.4.1, 0.5.0-0.5.4] or uninstalled
 ├─restricted to versions * by an explicit requirement, leaving only versions [0.1.0-0.1.1, 0.2.0, 0.3.0-0.3.1, 0.4.0-0.4.1, 0.5.0-0.5.4]
 └─restricted by julia compatibility requirements to versions: uninstalled — no versions left
```

Here I'm proposing that we make a v0.0.1 release with empty contents so that users can still install this package for Julia < v1.3. Given that this package is only one of the many IO backend that registered in FileIO,
it would just be fine as long as both `ImageMagick` and `ImageIO` are added; `FileIO` knows which one should be called when it tries to load an image.

This also makes it possible to bring Images.jl back to support Julia 1.0; maintaining multiple branches is a headache to me, so if possible I really wish I can avoid it.

For Julia >= v1.3, I think Pkg resolver will ends with a higher ImageIO version with real IO codes. Hence this v0.0.1 release should only affect users with Julia < v"1.3".

**Comment by johnnychen94** [comment]
I've made a `release-0.0.1` branch, if you think this is a good idea, I'll tag a release for it.

**Comment by IanButterworth** [comment]
Seems reasonable. Looking forward to being able to drop 1.0 support!

**Comment by johnnychen94** [comment]
Having 1.0 support means that we're having good code quality :)

But yes, it costs the time of maintainers; I do not yet have a strong reason to directly bump the whole JuliaImages stack to Julia 1.3/1.6. The new step range version of `CartesianIndices` is a perhaps good reason for me, though, but I'm still playing with it on my new experimental algorithms.
