### ISSUE TITLE
allow custom array types as return value: solving FileIO world-age issue

### ISSUE THREAD

**Issue by johnnychen94** [JuliaIO/ImageIO.jl#47]
There are two valid use cases here:

- indexed image: `IndirectArray`
- image with metadata: `ImageMeta` and arrays defined in TiffImages

The technical issue here is that FileIO loads ImageIO and PNGFiles during runtime, and it would cause world-age issues. Is there an easy workaround to solve this?

**Comment by johnnychen94** [comment]
> Is there an easy workaround to solve this?

For the specific indexed image case, the simple solution is to add `IndirectArrays` dependency to ImageIO. But I'm wondering if there's a generic fix to support arbitrary array types without adding too much latency.

**Comment by timholy** [comment]
Should we make the FileIO call with `invokelatest`? That would solve the world-age issue.

**Comment by johnnychen94** [comment]
I might misunderstand the issue here. It seems that the world-age issue is already "solved" somewhere.
