### ISSUE TITLE
tagbot not working

### ISSUE THREAD

**Issue by johnnychen94** [JuliaIO/ImageIO.jl#50]
In https://github.com/JuliaIO/ImageIO.jl/runs/6455647295?check_suite_focus=true
```
Error: TagBot experienced an unexpected internal failure
Traceback (most recent call last):
  File "/root/tagbot/action/__main__.py", line 94, in <module>
    repo.create_release(version, sha)
  File "/root/tagbot/action/repo.py", line 5[43](https://github.com/JuliaIO/ImageIO.jl/runs/6455647295?check_suite_focus=true#step:3:43), in create_release
    self._repo.create_git_ref(f"refs/tags/{version}", tag.sha)
  File "/usr/local/lib/python3.8/site-packages/github/Repository.py", line 969, in create_git_ref
    headers, data = self._requester.requestJsonAndCheck(
  File "/usr/local/lib/python3.8/site-packages/github/Requester.py", line 315, in requestJsonAndCheck
    return self.__check(
  File "/usr/local/lib/python3.8/site-packages/github/Requester.py", line 340, in __check
    raise self.__createException(status, responseHeaders, output)
github.GithubException.GithubException: 403 {"message": "Resource not accessible by integration", "documentation_url": "https://docs.github.com/rest/reference/git#create-a-reference"}

Response (200): {
  "status": "Submitted error report"
}
```

According to https://github.com/JuliaRegistries/TagBot/issues/222, I thought upgrading the config to the latest version https://github.com/JuliaIO/ImageIO.jl/commit/4a23cd6b10ea7c3ffa7712ae2593014b203dcc11 fixes it but still get the same error.

My guess right now is that the ssh key `DOCUMENTER_KEY` isn't working, @IanButterworth could you help check it?

**Comment by IanButterworth** [comment]
I haven't looked into it but I think there's an ongoing problem with tagbot https://discourse.julialang.org/t/slow-tagbot-no-repo-update-after-16-hours/80870

**Comment by johnnychen94** [comment]
Yeah, I've noticed this and https://github.com/JuliaRegistries/TagBot/pull/236 gives an updated config version. Yet it still doesn't work even if I've updated it in 4a23cd6 -- unsure why.

I don't have permission to https://github.com/JuliaIO/ImageIO.jl/settings so can't check if `DOCUMENTER_KEY` is configured or not.

**Comment by IanButterworth** [comment]
> I don't have permission to [JuliaIO/ImageIO.jl/settings](https://github.com/JuliaIO/ImageIO.jl/settings) so can't check if DOCUMENTER_KEY is configured or not.

~~Apparently I don't either~~ I do now

**Comment by IanButterworth** [comment]
Fixed

**Comment by jaakkor2** [comment]
Tag for ImageIO v0.6.7 is missing.  This commit https://github.com/JuliaIO/ImageIO.jl/commit/e947e647d8179d7c4f62f2691eec86002bdc439c should have triggered TagBot, but looks like it did not.
